apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hls2mpeg
spec:
  schedule: "1 15 * * *"
  concurrencyPolicy: "Allow"
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1 # set over count of cameras
      template:
        metadata:
          name: hls2mpeg
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hls2mpeg
              image: hls2mpeg
              imagePullPolicy: Always
              volumeMounts:
                - name: video-out
                  mountPath: /out
              lifecycle:
                preStop:
                  exec:
                    command: ["/app/sigterm.sh"]
          volumes:
            - name: video-out
              emptyDir: {} # set your own volume
