apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          imagePullPolicy: Always
          image: nginx-client
          ports:
            - containerPort: 80
          volumeMounts:
            - name: video
              mountPath: /var/www/html/mount
      volumes:
        - name: video
          emptyDir: {} # set your own volume
---
apiVersion: v1
kind: Service
metadata:
  name: monitor
spec:
  selector:
    app: monitor
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      name: http
