apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp2hls
spec:
  replicas: 1 # set count of cameras
  selector:
    matchLabels:
      app: rtsp2hls
  template:
    metadata:
      labels:
        app: rtsp2hls
    spec:
      containers:
        - name: rtsp2hls
          imagePullPolicy: Always
          image: rtsp2hls
          volumeMounts:
            - name: video-out
              mountPath: /out
            - mountPath: /app/config.csv
              name: rtsp2hls-conf
              subPath: config.csv
          lifecycle:
            preStop:
              exec:
                command: ["/app/sigterm.sh"]
      volumes:
        - name: video-out
          emptyDir: {} # set your own volume
        - name: rtsp2hls-conf
          configMap:
            name: rtsp2hls-conf
